# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configure to use our ssh key
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines(".ssh/vagrant_key.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> ~vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "humio" do |humio|
    ### Customize Specs (VB only) ###
    humio.vm.provider "virtualbox" do |vb|
      vb.check_guest_additions = false
      vb.memory = 8192
      vb.cpus = 4
    end

    # VM config
    humio.vm.hostname = "humio"
    humio.vm.network "private_network", ip: "10.1.1.2"
    humio.vm.box = "carlosmmatos/dockerhost"

    # Docker provisioning
    humio.vm.provision "docker" do |d|
      d.run "humio/humio",
        daemonize: true,
        args: %W[
          --pull always
          -v /vagrant/mounts/data:/data
          -v /vagrant/mounts/kafka-data:/data/kafka-data
          -v /vagrant/etc:/etc/humio:ro
          -p 8080:8080
          -p 9200:9200
          --name=humio
          --ulimit='nofile=8192:8192'
          --env-file=/vagrant/humio.conf].join(' ')
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.hostname = "centos2"
    centos.vm.network "private_network", ip: "10.1.1.3"
    centos.vm.box = "bento/centos-8.4"
    # Sets updated hostname in syslog messages
    centos.vm.provision "shell", inline: "systemctl restart syslog"
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu2"
    ubuntu.vm.network "private_network", ip: "10.1.1.4"
    ubuntu.vm.box = "hashicorp/bionic64"
    # Sets updated hostname in syslog messages
    ubuntu.vm.provision "shell", inline: "systemctl restart syslog"
  end

  config.vm.define "fedora" do |fedora|
    fedora.vm.hostname = "fedora2"
    fedora.vm.network "private_network", ip: "10.1.1.5"
    fedora.vm.box = "bento/fedora-latest"
    # Installing chkconfig helps with adding systemd services
    # via installation methods
    fedora.vm.provision "shell", inline: "dnf -y install chkconfig"
  end

end
